FROM python:3.10-slim

WORKDIR /app
RUN apt-get update && apt-get install -y ffmpeg
RUN pip install --no-cache-dir flask openai-whisper torch torchaudio

COPY asr/ .
EXPOSE 5001
CMD ["python", "whisper_server.py"]